LIN 373 UT Austin :: Jessy Li

## Naive Bayes

Let's encode the Naive Bayes example we used in class into the count table shown on the slides.

In [1]:
## Here's the data. Let's pretend these are grammatical sentences.
docs_train = ["Chinese Beijing Chinese",
              "Chinese Chinese Shanghai",
              "Chinese Macao",
             "Tokyo Japan Chinese"]
Y_train = [1, 1, 1, 0]

docs_test = ["Chinese Chinese Chinese Tokyo Japan"]

In [4]:
## first need to tokenize each document
docs_train_tokenized = [doc.split() for doc in docs_train]
docs_test_tokenized = [doc.split() for doc in docs_test]

print(docs_train_tokenized, docs_test_tokenized)


[['Chinese', 'Beijing', 'Chinese'], ['Chinese', 'Chinese', 'Shanghai'], ['Chinese', 'Macao'], ['Tokyo', 'Japan', 'Chinese']] [['Chinese', 'Chinese', 'Chinese', 'Tokyo', 'Japan']]


So how do we put words into a table?
First, we need to create that table. The rows are just the examples. But we need to come up with the columns.
We need to assign each word to a column number!
We do that by creating a dictionary to map from word to a unique column id:

In [7]:
word_to_col_id = {}
for doc in docs_train_tokenized:
    for word in doc:
        if word not in word_to_col_id:
            word_to_col_id[word] = len(word_to_col_id)
print(word_to_col_id)
    

{'Chinese': 0, 'Beijing': 1, 'Shanghai': 2, 'Macao': 3, 'Tokyo': 4, 'Japan': 5}


Now, we can make the table, and fill it up!

In [16]:
import numpy as np

X_train = np.zeros((len(docs_train),len(word_to_col_id)))

# column represents the word
# row represents the doc
for i, doc in enumerate(docs_train_tokenized):
    for word in doc:
        rowid = i
        colid = word_to_col_id[word]
        X_train[rowid][colid] += 1

print(X_train)

[[2. 1. 0. 0. 0. 0.]
 [2. 0. 1. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 1. 1.]]


We do the same for testing docs.

In [18]:
X_test = np.zeros((len(docs_test),len(word_to_col_id)))

for i, doc in enumerate(docs_test_tokenized):
    for word in doc:
        rowid = i
        if word in word_to_col_id:
            colid = word_to_col_id[word]
            X_test[rowid][colid] += 1

print(X_test)

[[3. 0. 0. 0. 1. 1.]]


In [23]:
## Implementing NB from scratch!
from collections import defaultdict

# two dictionaries - each class what is the probability of the prior
# single dict - variables as keys, probabilities as values

# second dictionary - what is it's conditional probability given the class
# nested dict

prior = [0,0]
conditional_probability = defaultdict(dict)
testprob = [0,0]

for c in [0, 1]:
    print('class', c)
    prior[c] = Y_train.count(c)/len(Y_train)
    #P(W1|C) = # of times W1 appeared in class c / number of words in class c



class 0
class 1


What if there is a new word in the testing docs?


### Using a tool

All of this is implemented by sklearn's [CountVectorizer](https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html#sklearn.feature_extraction.text.CountVectorizer), which does tokenization AND the corpus-to-table transformation

In [ ]:
## vectorizer uses sparse encoding


In [ ]:
## get the test vector


## Running the Naive Base model

Check https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html!